default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: <%= ENV["TEST_DATABASE_NAME"] %> # You can change this as per your preference

production:
  primary:
    <<: *default
    database: <%= ENV["DATABASE_NAME"] %>
    host: <%= ENV["DATABASE_HOST"] %>
    port: <%= ENV["DATABASE_PORT"] %>
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    
  cache:
    <<: *default
    database: <%= ENV["CACHE_DATABASE"] || 'storage/production_cache.sqlite3' %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    database: <%= ENV["QUEUE_DATABASE"] || 'storage/production_queue.sqlite3' %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: <%= ENV["CABLE_DATABASE"] || 'storage/production_cable.sqlite3' %>
    migrations_paths: db/cable_migrate

